version: '2'
services:
    jhipsterangularjsmd5-app:
        image: jhipsterangularjsmd5
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterangularjsmd5-mysql:3306/jhipsterangularjsmd5?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterangularjsmd5-mysql:
        extends:
            file: mysql.yml
            service: jhipsterangularjsmd5-mysql
